# Generated by Django 4.0.2 on 2022-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
