# Generated by Django 4.0.2 on 2022-10-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_manufacturer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
