# Generated by Django 4.0.2 on 2022-10-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_car_slug_driver_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='slug',
        ),
    ]
